import type { Metadata } from "next";
import "@/app/globals.css";
import { getMessages, getTranslations } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import {unstable_setRequestLocale} from 'next-intl/server';
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string}
}>) {
  unstable_setRequestLocale(locale)

  const messages = await getMessages();
  const t = await getTranslations();

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="font-sans">
        <NextIntlClientProvider messages={messages}>
          {/* Wrapping content in a Flexbox container */}
          <div className="flex flex-col min-h-screen">
            {/* Navbar at the top */}
            <Navbar locale={locale} />

            {/* Main content (children) grows to fill available space */}
            <main className="flex-grow">
              {children}
            </main>

            {/* Footer sticks to the bottom */}
            <Footer t={t} />  {/* Pass messages to Footer */}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
